# Basic config
baseURL = "/"
theme = "terminal"
paginate = 5
languageCode = "en-us"

[params]
  # dir name of your main content (default is `content/posts`).
  # the list of set content will show up on your index page (baseurl).
  contentTypeName = "posts"

  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 2

  # show selector to switch language
  showLanguageSelector = false

  # set theme to full screen width
  fullWidthTheme = false

  # center theme with default width
  centerTheme = false

  # if your resource directory contains an image called `cover.(jpg|png|webp)`,
  # then the file will be used as a cover automatically.
  # With this option you don't have to put the `cover` param in a front-matter.
  autoCover = true

  # set post to show the last updated
  # If you use git, you can set `enableGitInfo` to `true` and then post will automatically get the last updated
  showLastUpdated = false

  # Provide a string as a prefix for the last update date. By default, it looks like this: 2020-xx-xx [Updated: 2020-xx-xx] :: Author
  # updatedDatePrefix = "Updated"

  # whether to show a page's estimated reading time
  # readingTime = false # default

  # whether to show a table of contents
  # can be overridden in a page's front-matter
  # Toc = false # default

  # set title for the table of contents
  # can be overridden in a page's front-matter
  # TocTitle = "Table of Contents" # default

  # Set date/time format for posts
  # This will impact the date/time displayed on
  # index.html, the posts list page, and on posts themselves
  # This value can also be configured per-post on front matter
  # If you have any issues with the timezone rendering differently
  # than you expected, please ensure your timezone is correctly set
  # on your server.
  # This value can be customized according to Hugo documentation:
  # https://gohugo.io/functions/time/format/
  # Default value (no changes needed):
  # dateFormat = "2006-01-02"
  # Example format, with date, time, and timezone abbreviation:
  # dateFormat = "2006-01-02 3:04:06 PM MST"


[params.twitter]
  # set Twitter handles for Twitter cards
  # see https://developer.twitter.com/en/docs/tweets/optimize-with-cards/guides/getting-started#card-and-content-attribution
  # do not include @
  creator = ""
  site = ""

[languages]
  [languages.en]
    languageName = "English"
    title = "Leopoldo Mu침oz - DevOps Engineer"

    [languages.en.params]
      subtitle = "Personal Site / Portfolio / Blog"
      owner = "Leopoldo Mu침oz"
      keywords = "devops,engineer,developer,it,specialist"
      copyright = ""
      menuMore = "Show more"
      readMore = "Read more"
      readOtherPosts = "Read other posts"
      newerPosts = "Newer posts"
      olderPosts = "Older posts"
      missingContentMessage = "Page not found..."
      missingBackButtonLabel = "Back to home page"
      minuteReadingTime = "min read"
      words = "words"

      [languages.en.params.logo]
        logoText = "Leopoldo Mu침oz"
        logoHomeLink = "/"

      [languages.en.menu]
        [[languages.en.menu.main]]
          identifier = "about"
          name = "About"
          url = "/about"
        [[languages.en.menu.main]]
          identifier = "showcase"
          name = "Showcase"
          url = "/showcase"

[module]
[[module.imports]]
  path = 'terminal'



# copyright = "Leopoldo Mu침oz"
# defaultContentLanguage = "en"

# # Generate a nice robots.txt for SEO
# enableRobotsTXT = true

# # Setup syntax highlighting without inline styles. For more information about
# # why you'd want to avoid inline styles, see
# # https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/style-src#unsafe_inline_styles
# [markup]
#   [markup.highlight]
#     lineNos = true
#     lineNumbersInTable = false
#     # This allows Bear Cub to use a variation of Dracula that is more accessible
#     # to people with poor eyesight. For more information about color contrast
#     # and accessibility, see https://web.dev/color-and-contrast-accessibility/
#     noClasses = false

# # Multilingual mode config. More for information about how to setup translation,
# # see https://gohugo.io/content-management/multilingual/
# [languages]
#   [languages.en]
#     title = "viceo.mx"
#     languageName = "en-US 游쥟릖"
#     LanguageCode = "en-US"
#     contentDir = "content"
#     [languages.en.params]
#       madeWith = "Made with [Bear Cub](https://github.com/clente/hugo-bearcub)"
# #   [languages.es]
# #     title = "viceo.mx"
# #     languageName = "es-MX es"
# #     LanguageCode = "es-MX"
# #     contentDir = "content.es"
# #     [languages.pt.params]
# #       madeWith = "Hecho con [Bear Cub](https://github.com/clente/hugo-bearcub)"

# [params]
#   # The description of your website
#   description = "Leopoldo Mu침oz's Personal Website"

#   # The path to your favicon
#   favicon = "favicon.ico"

#   # These images will show up when services want to generate a preview of a link
#   # to your site. Ignored if `generateSocialCard = true`. For more information
#   # about previews, see https://gohugo.io/templates/internal#twitter-cards and
#   # https://gohugo.io/templates/internal#open-graph
# #   images = ["images/share.webp"]

#   # This title is used as the site_name on the Hugo's internal opengraph
#   # structured data template
#   title = "viceo.mx"

#   # Dates are displayed following the format below. For more information about
#   # formatting, see https://gohugo.io/functions/format/
#   dateFormat = "2006-01-02"

#   # If your blog is multilingual but you haven't translated a page, this theme
#   # will create a disabled link. By setting `hideUntranslated` to true, you can
#   # have the theme simply not show any link
#   hideUntranslated = true

#   # (EXPERIMENTAL) This theme has two options for its CSS styles: "original" and
#   # "herman". The former is what you see on Bear Cub's demo (an optimized
#   # version of Hugo Bear Blog), while the latter has a more modern look based on
#   # Herman Martinus's version of the Blogster Minimal theme for Astro.
#   themeStyle = "original"

#   # (EXPERIMENTAL) This theme is capable of dynamically generating social cards
#   # for posts that don't have `images` defined in their front matter; By setting
#   # `generateSocialCard` to false, you can prevent this behavior. For more
#   # information see layouts/partials/social_card.html
#   generateSocialCard = true

#   # Social media. Delete any item you aren't using to make sure it won't show up
#   # in your website's metadata.
#   [params.social]
#     twitter = "example" # Twitter handle (without '@')
#     facebook_admin = "0000000000" # Facebook Page Admin ID

#   # Author metadata. This is mostly used for the RSS feed of your site, but the
#   # email is also added to the footer of each post. You can hide the "reply to"
#   # link by using a `hideReply` param in front matter.
#   [params.author]
#     name = "John Doe" # Your name as shown in the RSS feed metadata
#     email = "me@example.com" # Added to the footer so readers can reply to posts